apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  labels:
    app: email-sevice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - image: docker.io/sajith75/email-service
        name: email-service
        ports:
        - containerPort: 3000
