apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
  labels:
    app: group-sevice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-service
  template:
    metadata:
      labels:
        app: group-service
    spec:
      containers:
      - image: docker.io/sajith75/group-service
        name: group-service
        ports:
        - containerPort: 3000
