apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-service
  labels:
    app: secret-sevice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-service
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
      - image: docker.io/sajith75/secret-service
        name: secret-service
        ports:
        - containerPort: 3000
